import { useEffect, useState } from 'react'
import api from '../api/client.js'

export default function SpecializedComponentPanel({ component, profile, busy, setNotice }) {
  const [sensors,setSensors]=useState([]); const [sensor,setSensor]=useState({name:'',reading_type:'',unit:'',min_value:'',max_value:''}); const [readings,setReadings]=useState([]); const [value,setValue]=useState('')
  const load=async()=>{try{setSensors(await api.get(`/api/components/${component.id}/sensors`)); setReadings(await api.get(`/api/components/${component.id}/readings?limit=40`))}catch(e){setNotice(e.message)}}
  useEffect(()=>{if(component?.id)load()},[component?.id])
  const addSensor=async e=>{e.preventDefault();try{await api.post(`/api/components/${component.id}/sensors`,{...sensor,min_value:sensor.min_value===''?null:Number(sensor.min_value),max_value:sensor.max_value===''?null:Number(sensor.max_value)});setSensor({name:'',reading_type:'',unit:'',min_value:'',max_value:''});load()}catch(e){setNotice(e.message)}}
  const addReading=async e=>{e.preventDefault();const s=sensors[0];if(!s||value==='')return;try{await api.post(`/api/components/${component.id}/readings`,{sensor_id:s.id,reading_type:s.reading_type,value:Number(value),unit:s.unit||null,source:'manual'});setValue('');load()}catch(e){setNotice(e.message)}}
  if(!component)return <div className="sp-note">Select a component to inspect its independent sensors and readings.</div>
  return <div className="sp-component-workspace">
    <div className="sp-note"><strong>{component.name}</strong><div style={{color:'var(--text-faint)',marginTop:4}}>{profile.name} component · independent telemetry channel</div></div>
    <div className="sp-layout" style={{marginTop:10}}>
      <section className="panel"><div className="panel-header"><span className="panel-title">Sensors</span><small>{sensors.length} configured</small></div><div className="panel-body sp-list">{sensors.map(s=><div className="sp-row" key={s.id}><span><strong>{s.name}</strong><small>{s.reading_type}</small></span><strong>{s.unit||'unitless'}</strong></div>)}{!sensors.length&&<small style={{color:'var(--text-faint)'}}>No sensors configured for this component.</small>}<form className="sp-form" onSubmit={addSensor} style={{marginTop:12}}><label>Sensor name<input required value={sensor.name} onChange={e=>setSensor({...sensor,name:e.target.value})} placeholder="e.g. Joint torque sensor" /></label><label>Reading type<input required value={sensor.reading_type} onChange={e=>setSensor({...sensor,reading_type:e.target.value})} placeholder="e.g. joint_1_torque" /></label><label>Unit<input value={sensor.unit} onChange={e=>setSensor({...sensor,unit:e.target.value})} placeholder="Nm" /></label><button className="btn" disabled={busy}>Add sensor</button></form></div></section>
      <section className="panel"><div className="panel-header"><span className="panel-title">Component readings</span><small>Persisted independently</small></div><div className="panel-body"><div className="sp-grid">{sensors.map(s=>{const r=readings.find(x=>x.sensor_id===s.id)||readings.find(x=>x.reading_type===s.reading_type);return <div className="sp-reading" key={s.id}><small>{s.name}</small><strong>{r?`${Number(r.value).toFixed(2)} ${r.unit||s.unit||''}`:'—'}</strong><small>{s.reading_type}</small></div>})}</div>{sensors.length>0&&<form className="sp-form" onSubmit={addReading} style={{marginTop:12}}><label>Manual reading<select value={sensors[0].id} disabled><option>{sensors[0].name}</option></select></label><label>Value<input type="number" step="any" value={value} onChange={e=>setValue(e.target.value)} required /></label><button className="btn" disabled={busy}>Record reading</button></form>}<div className="sp-list" style={{marginTop:12}}>{readings.slice(0,12).map(r=><div className="sp-row" key={r.id}><span>{r.reading_type}</span><strong>{Number(r.value).toFixed(2)} {r.unit||''}</strong></div>)}</div></div></section>
    </div>
  </div>
}
