import { useEffect, useMemo, useState } from 'react'
import { useNavigate, useParams } from 'react-router-dom'
import api from '../api/client.js'
import StatusBadge from './StatusBadge.jsx'
import { ErrorState, Loading } from '../pages/Dashboard.jsx'
import { usePageHeader } from '../PageHeaderContext.jsx'
import { getSpecializedMachineProfile } from '../config/specializedMachineProfiles.js'

const norm = x => String(x ?? '').toLowerCase().replace(/[^a-z0-9]+/g, '_').replace(/^_|_$/g, '')
const ROBOT_TYPES = { articulated:'Articulated', scara:'SCARA', cartesian:'Cartesian / Gantry', delta:'Parallel / Delta', cylindrical:'Cylindrical', spherical:'Spherical / Polar', cobot:'Collaborative Robot', humanoid:'Humanoid' }
const specializedBase = ['cnc','robot','drill_press','grinding_machine','hydraulic_press','injection_molding','packaging_machine','generator','transformer','boiler','furnace','hvac','fan_blower','gearbox','turbine','crane_hoist','agv_amr','water_treatment','other']

function baseCategory(category){ const raw=String(category||'other'); if(raw.startsWith('robot_')) return 'robot'; return specializedBase.includes(raw)?raw:'other' }
function robotType(category){ return String(category||'').startsWith('robot_') ? String(category).slice(6) : 'articulated' }
function readingMap(rows, live){ const map={}; rows.forEach(r=>{map[norm(r.reading_type)] = r}); Object.entries(live).forEach(([k,v])=>{map[norm(k)] = v}); return map }
function formatReading(item){ if(!item) return '—'; const n=Number(item.value); return Number.isFinite(n)?`${n.toFixed(2)} ${item.unit||''}`.trim():String(item.value) }
function Card({label,value,sub}){return <div className="sp-card"><span>{label}</span><strong>{value}</strong>{sub&&<small>{sub}</small>}</div>}

export default function SpecializedMachineDetail({machine:initialMachine}){
 const {id}=useParams(); const navigate=useNavigate(); const [machine,setMachine]=useState(initialMachine); const [rows,setRows]=useState([]); const [live,setLive]=useState({}); const [components,setComponents]=useState([]); const [maintenance,setMaintenance]=useState([]); const [device,setDevice]=useState(null); const [safety,setSafety]=useState(null); const [intelligence,setIntelligence]=useState(null); const [degradation,setDegradation]=useState([]); const [tab,setTab]=useState('Overview'); const [selected,setSelected]=useState(null); const [busy,setBusy]=useState(false); const [notice,setNotice]=useState(''); const [newComponent,setNewComponent]=useState(''); const [deviceKey,setDeviceKey]=useState(''); const [forecast,setForecast]=useState(null)
 const profile=getSpecializedMachineProfile(machine?.category); const base=baseCategory(machine?.category); const map=useMemo(()=>readingMap(rows,live),[rows,live]); const health=Number(machine?.health_score||0)
 const load=async()=>{try{const results=await Promise.allSettled([api.get(`/api/machines/${id}`),api.get(`/api/machines/${id}/readings?limit=200`),api.get(`/api/machines/${id}/components`),api.get(`/api/maintenance?machine_id=${id}&limit=100`),api.get(`/api/devices/${id}/status`),api.get(`/api/devices/${id}/safety`),api.get(`/api/analytics/machines/${id}/intelligence`),api.get(`/api/analytics/machines/${id}/degradation?limit=48`)]); if(results[0].status==='fulfilled')setMachine(results[0].value); if(results[1].status==='fulfilled')setRows(results[1].value||[]); if(results[2].status==='fulfilled')setComponents(results[2].value||[]); if(results[3].status==='fulfilled')setMaintenance(results[3].value||[]); if(results[4].status==='fulfilled')setDevice(results[4].value); if(results[5].status==='fulfilled')setSafety(results[5].value); if(results[6].status==='fulfilled')setIntelligence(results[6].value); if(results[7].status==='fulfilled')setDegradation(results[7].value?.points||[])}catch(e){setNotice(e.message||'Unable to load specialized machine')}}
 useEffect(()=>{load()},[id])
 useEffect(()=>{const onTelemetry=e=>{const d=e.detail;if(String(d?.machine_id)!==String(id)||d.type!=='telemetry')return;setLive(p=>({...p,[norm(d.reading_type)]:d}))}; window.addEventListener('maintain-ai-telemetry',onTelemetry); return()=>window.removeEventListener('maintain-ai-telemetry',onTelemetry)},[id])
 useEffect(()=>{const t=setInterval(()=>load(),15000);return()=>clearInterval(t)},[id])
 usePageHeader(<span className="sp-head"><button className="btn secondary" onClick={()=>navigate('/machines')}>← Back</button><span>{machine?.name||'Machine'}</span></span>,machine?<StatusBadge status={machine.status}/>:null)
 const addComponent=async e=>{e.preventDefault();if(!newComponent.trim())return;setBusy(true);try{await api.post(`/api/machines/${id}/components`,{name:newComponent.trim()});setNewComponent('');await load();setNotice('Component added.')}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 const provision=async()=>{setBusy(true);try{const r=await api.post(`/api/devices/${id}/enable`,{});setDevice(r);setDeviceKey(r?.device_key||'');setNotice('Device provisioned. Store the key securely; it may only be returned during provisioning.')}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 const disable=async()=>{setBusy(true);try{setDevice(await api.post(`/api/devices/${id}/disable`,{}));setDeviceKey('');setNotice('Device integration disabled.')}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 const testShutdown=async()=>{setBusy(true);try{await api.post(`/api/devices/${id}/safety/test-shutdown`,{});setNotice('Safety shutdown test command queued.')}catch(e){setNotice(e.message)}finally{setBusy(false)}}
 const runForecast=async()=>{setBusy(true);try{setForecast(await api.get(`/api/analytics/machines/${id}/forecast?reading_type=${encodeURIComponent(profile.predictions[0]||'temperature')}&model=chronos-bolt-tiny&horizon=12`))}catch(e){setForecast({error:e.message})}finally{setBusy(false)}}
 if(!machine)return <Loading/>; const signalGroups=[{title:'Primary process signals',items:profile.telemetry},{title:'Prediction signals',items:profile.predictions.map(k=>profile.telemetry.find(x=>x[0]===k)||[k,k,''])}];
 return <><style>{`.sp{display:flex;flex-direction:column;gap:14px}.sp-head{display:flex;gap:10px;align-items:center}.sp-hero{padding:20px;border:1px solid var(--border);border-radius:16px;background:linear-gradient(135deg,rgba(59,130,246,.10),rgba(15,23,42,.18))}.sp-kicker{font-size:10px;text-transform:uppercase;letter-spacing:.13em;color:var(--text-faint);font-weight:800}.sp-title{font-size:25px;font-weight:850;margin:4px 0}.sp-sub{color:var(--text-faint);font-size:12px}.sp-cards{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:9px;margin-top:16px}.sp-card{border:1px solid var(--border);border-radius:11px;padding:12px;background:rgba(15,23,42,.22)}.sp-card span,.sp-card small{display:block;color:var(--text-faint);font-size:10px;text-transform:uppercase;letter-spacing:.06em}.sp-card strong{display:block;font-size:16px;margin-top:5px}.sp-tabs{display:flex;gap:6px;overflow:auto}.sp-tab{padding:9px 12px;border:1px solid var(--border);border-radius:9px;background:var(--panel);color:var(--text-dim);font-weight:700;white-space:nowrap;cursor:pointer}.sp-tab.active{color:var(--text);border-color:var(--accent)}.sp-layout{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.sp-grid{display:grid;grid-template-columns:repeat(3,minmax(0,1fr));gap:8px}.sp-reading{padding:11px;border:1px solid var(--border);border-radius:10px}.sp-reading small{display:block;color:var(--text-faint)}.sp-reading strong{display:block;margin-top:5px}.sp-list{display:flex;flex-direction:column}.sp-row{display:flex;justify-content:space-between;gap:12px;padding:10px 0;border-bottom:1px solid var(--border);font-size:12px}.sp-row:last-child{border:0}.sp-form{display:flex;gap:8px;align-items:end;flex-wrap:wrap}.sp-form label{display:flex;flex-direction:column;gap:5px;color:var(--text-faint);font-size:10px;font-weight:700}.sp-form input,.sp-form select{min-width:150px}.sp-component{padding:13px;border:1px solid var(--border);border-radius:11px;background:var(--panel);cursor:pointer;text-align:left;color:var(--text)}.sp-component.active{border-color:var(--accent)}.sp-components{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:8px}.sp-note{padding:11px;border:1px solid var(--border);border-radius:9px;font-size:11px}.sp-danger{border-color:rgba(239,68,68,.5);background:rgba(239,68,68,.07)}.sp-key{font-family:monospace;word-break:break-all;border:1px dashed var(--border);padding:10px;border-radius:8px;margin-top:10px}.sp-bars{display:flex;gap:3px;height:55px;align-items:end}.sp-bars i{width:7px;background:var(--accent);border-radius:4px 4px 0 0}@media(max-width:900px){.sp-layout{grid-template-columns:1fr}.sp-cards{grid-template-columns:repeat(2,1fr)}}@media(max-width:600px){.sp-cards,.sp-grid,.sp-components{grid-template-columns:1fr}}`}</style>
 <main className="sp"><section className="sp-hero"><div className="sp-kicker">{profile.name}</div><div className="sp-title">{machine.name}</div><div className="sp-sub">{profile.subtitle} · {machine.machine_code||'No code'} · {machine.location||'Location not set'}</div>{base==='robot'&&<div style={{marginTop:12}}><span className="sp-kicker">Robot architecture</span><div style={{fontWeight:800,fontSize:15,marginTop:3}}>{ROBOT_TYPES[robotType(machine.category)]||robotType(machine.category)}</div></div>}<div className="sp-cards"><Card label="Health" value={`${health}/100`} sub={intelligence?.risk_level||'Condition'} /><Card label="Status" value={machine.status||'—'} /><Card label="Live signals" value={Object.keys(live).length} sub="realtime updates" /><Card label="Components" value={components.length} /></div></section>
 <nav className="sp-tabs">{['Overview','Components','Safety','Health','Predictions','Maintenance','Telemetry'].map(x=><button className={`sp-tab ${tab===x?'active':''}`} key={x} onClick={()=>setTab(x)}>{x}</button>)}</nav>{notice&&<div className="sp-note">{notice}</div>}
 {tab==='Overview'&&<><div className="sp-layout">{signalGroups.map(g=><section className="panel" key={g.title}><div className="panel-header"><span className="panel-title">{g.title}</span><small>Category-specific telemetry</small></div><div className="panel-body sp-grid">{g.items.map(([key,label,unit])=><div className="sp-reading" key={key}><small>{label}</small><strong>{formatReading(map[norm(key)])}</strong><small>{unit}</small></div>)}</div></section>)}</div><div className="sp-layout"><section className="panel"><div className="panel-header"><span className="panel-title">Machine-specific hazards</span></div><div className="panel-body sp-list">{profile.hazards.map(h=><div className="sp-row" key={h}><span>{h.replaceAll('_',' ')}</span><strong>Safety rule</strong></div>)}</div></section><section className="panel"><div className="panel-header"><span className="panel-title">Predictive condition</span></div><div className="panel-body sp-grid"><Card label="Risk" value={intelligence?.risk_level||intelligence?.risk||'—'}/><Card label="Trend" value={intelligence?.trend||'—'}/><Card label="Degradation" value={degradation.length}/></div></section></div></>}
 {tab==='Components'&&<section className="panel"><div className="panel-header"><span className="panel-title">{profile.name} component tree</span><small>Each component can own independent telemetry</small></div><div className="panel-body"><div className="sp-components">{components.map(c=><button key={c.id} className={`sp-component ${selected?.id===c.id?'active':''}`} onClick={()=>setSelected(c)}><strong>{c.name}</strong><div style={{color:'var(--text-faint)',fontSize:10,marginTop:4}}>#{c.id} · {c.status||'configured'}</div></button>)}</div>{selected&&<div className="sp-note" style={{marginTop:10}}><strong>{selected.name}</strong><div className="sp-row"><span>Independent readings</span><strong>Enabled by telemetry type</strong></div><div className="sp-row"><span>Component ID</span><strong>#{selected.id}</strong></div></div>}<form className="sp-form" onSubmit={addComponent} style={{marginTop:12}}><label style={{flex:1}}>Add machine-specific component<input value={newComponent} onChange={e=>setNewComponent(e.target.value)} placeholder={base==='robot'?'e.g. J1 servo, wrist, gripper, vision camera':'e.g. bearing, pump, controller'} required /></label><button className="btn" disabled={busy}>Add component</button></form></div></section>}
 {tab==='Safety'&&<div className="sp-layout"><section className="panel"><div className="panel-header"><span className="panel-title">{profile.name} safety model</span><small>Uses existing persistent safety engine</small></div><div className="panel-body sp-list">{profile.safety.map(s=><div className="sp-row" key={s.signal}><span>{s.label}<small>{s.signal}</small></span><strong>Warn {s.warning.join('–')} · Shutdown {s.shutdown.join('–')}</strong></div>)}</div></section><section className="panel"><div className="panel-header"><span className="panel-title">Safety controls</span></div><div className="panel-body"><div className="sp-row"><span>Configured policies</span><strong>{safety?.policies?.length||0}</strong></div><div className="sp-row"><span>Automatic shutdown</span><strong>{safety?.policies?.some(p=>p.auto_shutdown_enabled)?'Enabled':'Not enabled'}</strong></div><button className="btn secondary" disabled={busy||!device?.iot_enabled} onClick={testShutdown}>Test shutdown command</button></div></section></div>}
 {tab==='Health'&&<div className="sp-layout"><section className="panel"><div className="panel-header"><span className="panel-title">Health telemetry</span></div><div className="panel-body sp-grid">{profile.telemetry.map(([key,label,unit])=><div className="sp-reading" key={key}><small>{label}</small><strong>{formatReading(map[norm(key)])}</strong><small>{unit}</small></div>)}</div></section><section className="panel"><div className="panel-header"><span className="panel-title">Degradation history</span></div><div className="panel-body">{degradation.length?<div className="sp-bars">{degradation.map((p,i)=><i key={i} style={{height:`${Math.max(5,Math.min(100,Number(p.score??p.health_score??p.value??0)))}%`}} />)}</div>:<span style={{color:'var(--text-faint)',fontSize:11}}>No degradation history available.</span>}</div></section></div>}
 {tab==='Predictions'&&<div className="sp-layout"><section className="panel"><div className="panel-header"><span className="panel-title">{profile.name} forecasting</span><small>Chronos-Bolt-Tiny</small></div><div className="panel-body"><button className="btn" disabled={busy} onClick={runForecast}>Run {profile.predictions[0]?.replaceAll('_',' ')} forecast</button>{forecast?.error&&<div className="sp-note sp-danger" style={{marginTop:10}}>{forecast.error}</div>}{forecast&&!forecast.error&&<div className="sp-note" style={{marginTop:10}}>Forecast generated using {forecast.model||'chronos-bolt-tiny'} for {forecast.reading_type||profile.predictions[0]}. Points: {forecast.points?.length||forecast.forecast?.length||'available'}.</div>}</div></section><section className="panel"><div className="panel-header"><span className="panel-title">Signals selected for prediction</span></div><div className="panel-body sp-list">{profile.predictions.map(k=><div className="sp-row" key={k}><span>{k.replaceAll('_',' ')}</span><strong>Prediction signal</strong></div>)}</div></section></div>}
 {tab==='Maintenance'&&<section className="panel"><div className="panel-header"><span className="panel-title">Maintenance history</span><small>{maintenance.length} records</small></div><div className="panel-body sp-list">{maintenance.map(m=><div className="sp-row" key={m.id}><span>{m.title||m.description||'Maintenance'}</span><strong>{m.status||'—'}</strong></div>)}{!maintenance.length&&<span style={{color:'var(--text-faint)',fontSize:11}}>No maintenance records.</span>}</div></section>}
 {tab==='Telemetry'&&<div className="sp-layout"><section className="panel"><div className="panel-header"><span className="panel-title">Device & keys</span></div><div className="panel-body"><div className="sp-row"><span>IoT integration</span><strong>{device?.iot_enabled?'Enabled':'Disabled'}</strong></div><div className="sp-row"><span>Device key</span><strong>{device?.has_key?'Provisioned':'Not provisioned'}</strong></div>{device?.iot_enabled?<button className="btn secondary" disabled={busy} onClick={disable}>Disable integration</button>:<button className="btn" disabled={busy} onClick={provision}>Enable & provision</button>}{deviceKey&&<div className="sp-key">{deviceKey}</div>}</div></section><section className="panel"><div className="panel-header"><span className="panel-title">Realtime telemetry</span></div><div className="panel-body sp-grid">{profile.telemetry.map(([key,label,unit])=><div className="sp-reading" key={key}><small>{label}</small><strong>{formatReading(map[norm(key)])}</strong><small>{unit}</small></div>)}</div></section></div>}
 </main></>
}
