const r = (id, name, architecture, components, telemetry, predictions, hazards, safety) => ({ id, name, architecture, components, telemetry, predictions, hazards, safety })

export const ROBOT_PROFILES = {
  articulated: r('articulated','Articulated Robot','Serial multi-joint arm',
    ['Base','J1 Axis','J2 Axis','J3 Axis','J4 Axis','J5 Axis','J6 Axis','Controller','End Effector','Safety System'],
    [['j1_position','J1 Position','°'],['j1_torque','J1 Torque','Nm'],['j1_temperature','J1 Temperature','°C'],['j2_position','J2 Position','°'],['j2_torque','J2 Torque','Nm'],['j2_temperature','J2 Temperature','°C'],['j3_position','J3 Position','°'],['j3_torque','J3 Torque','Nm'],['j4_position','J4 Position','°'],['j5_position','J5 Position','°'],['j6_position','J6 Position','°'],['controller_temperature','Controller Temperature','°C'],['servo_current','Servo Current','A'],['grip_force','End-Effector Force','N']],
    ['j1_torque','j2_torque','j3_torque','servo_current','controller_temperature'], ['joint_limit','servo_overcurrent','joint_overtemperature','collision','guard_interlock','emergency_stop'],
    [{signal:'controller_temperature',label:'Controller overtemperature',warning:[0,55],shutdown:[0,65]},{signal:'servo_current',label:'Servo overcurrent',warning:[0,8],shutdown:[0,12]}]),
  scara: r('scara','SCARA Robot','Selective Compliance Assembly Robot Arm',
    ['Base','J1 Rotary Axis','J2 Rotary Axis','Z Linear Axis','Theta Axis','Controller','End Effector','Safety System'],
    [['j1_angle','J1 Angle','°'],['j2_angle','J2 Angle','°'],['z_position','Z Position','mm'],['theta','Theta','°'],['j1_torque','J1 Torque','Nm'],['j2_torque','J2 Torque','Nm'],['z_force','Z Force','N'],['servo_current','Servo Current','A'],['controller_temperature','Controller Temperature','°C'],['cycle_time','Cycle Time','s']],
    ['j1_torque','j2_torque','z_force','servo_current','cycle_time'], ['joint_limit','z_axis_limit','servo_overcurrent','collision','guard_interlock','emergency_stop'],
    [{signal:'servo_current',label:'Servo overcurrent',warning:[0,8],shutdown:[0,12]},{signal:'z_force',label:'Z-axis force limit',warning:[0,400],shutdown:[0,500]}]),
  cartesian: r('cartesian','Cartesian / Gantry Robot','Linear X/Y/Z axes',
    ['X Axis','Y Axis','Z Axis','Linear Drives','Controller','End Effector','Safety System'],
    [['x_position','X Position','mm'],['y_position','Y Position','mm'],['z_position','Z Position','mm'],['x_velocity','X Velocity','mm/s'],['y_velocity','Y Velocity','mm/s'],['z_velocity','Z Velocity','mm/s'],['x_current','X Motor Current','A'],['y_current','Y Motor Current','A'],['z_current','Z Motor Current','A'],['controller_temperature','Controller Temperature','°C']],
    ['x_current','y_current','z_current','controller_temperature'], ['axis_limit','drive_overcurrent','collision','guard_interlock','emergency_stop'],
    [{signal:'x_current',label:'X drive overcurrent',warning:[0,8],shutdown:[0,12]},{signal:'y_current',label:'Y drive overcurrent',warning:[0,8],shutdown:[0,12]},{signal:'z_current',label:'Z drive overcurrent',warning:[0,8],shutdown:[0,12]}]),
  delta: r('delta','Delta / Parallel Robot','Parallel-arm high-speed robot',
    ['Frame','Arm A','Arm B','Arm C','Parallel Joint Set','Controller','End Effector','Safety System'],
    [['arm_a_position','Arm A Position','mm'],['arm_b_position','Arm B Position','mm'],['arm_c_position','Arm C Position','mm'],['arm_a_current','Arm A Current','A'],['arm_b_current','Arm B Current','A'],['arm_c_current','Arm C Current','A'],['end_effector_position','End-Effector Position','mm'],['controller_temperature','Controller Temperature','°C'],['cycle_time','Cycle Time','s']],
    ['arm_a_current','arm_b_current','arm_c_current','controller_temperature'], ['parallel_joint_fault','drive_overcurrent','workspace_limit','collision','guard_interlock','emergency_stop'],
    [{signal:'arm_a_current',label:'Arm A overcurrent',warning:[0,8],shutdown:[0,12]},{signal:'arm_b_current',label:'Arm B overcurrent',warning:[0,8],shutdown:[0,12]},{signal:'arm_c_current',label:'Arm C overcurrent',warning:[0,8],shutdown:[0,12]}]),
  cylindrical: r('cylindrical','Cylindrical Robot','Rotary base with radial/vertical motion',
    ['Base Rotation','Radial Axis','Vertical Axis','Controller','End Effector','Safety System'],
    [['base_angle','Base Angle','°'],['radial_position','Radial Position','mm'],['vertical_position','Vertical Position','mm'],['base_current','Base Motor Current','A'],['radial_current','Radial Motor Current','A'],['vertical_current','Vertical Motor Current','A'],['controller_temperature','Controller Temperature','°C']],
    ['base_current','radial_current','vertical_current','controller_temperature'], ['axis_limit','drive_overcurrent','collision','guard_interlock','emergency_stop'],
    [{signal:'vertical_current',label:'Vertical drive overcurrent',warning:[0,8],shutdown:[0,12]}]),
  spherical: r('spherical','Spherical / Polar Robot','Polar arm with rotary and radial motion',
    ['Base','Shoulder Axis','Elbow/Radial Axis','Wrist','Controller','End Effector','Safety System'],
    [['base_angle','Base Angle','°'],['shoulder_angle','Shoulder Angle','°'],['radial_position','Radial Position','mm'],['wrist_angle','Wrist Angle','°'],['base_current','Base Current','A'],['shoulder_current','Shoulder Current','A'],['radial_current','Radial Current','A'],['controller_temperature','Controller Temperature','°C']],
    ['base_current','shoulder_current','radial_current','controller_temperature'], ['axis_limit','drive_overcurrent','collision','guard_interlock','emergency_stop'],
    [{signal:'shoulder_current',label:'Shoulder drive overcurrent',warning:[0,8],shutdown:[0,12]}]),
  cobot: r('cobot','Collaborative Robot','Force/torque monitored collaborative arm',
    ['Robot Base','Joint 1','Joint 2','Joint 3','Joint 4','Joint 5','Joint 6','Force/Torque Sensor','Controller','Safety System'],
    [['joint_1_position','J1 Position','°'],['joint_2_position','J2 Position','°'],['joint_3_position','J3 Position','°'],['joint_4_position','J4 Position','°'],['joint_5_position','J5 Position','°'],['joint_6_position','J6 Position','°'],['joint_torque','Joint Torque','Nm'],['external_force','External Force','N'],['controller_temperature','Controller Temperature','°C'],['speed','TCP Speed','mm/s']],
    ['joint_torque','external_force','controller_temperature','speed'], ['power_limit','force_limit','protective_stop','safety_scanner','collision','emergency_stop'],
    [{signal:'external_force',label:'External force limit',warning:[0,80],shutdown:[0,120]},{signal:'speed',label:'Collaborative speed limit',warning:[0,1000],shutdown:[0,1500]}]),
  humanoid: r('humanoid','Humanoid Robot','Bipedal multi-limb robot',
    ['Head','Torso','Left Arm','Right Arm','Left Leg','Right Leg','Hands','Controller','Battery','Perception/Safety System'],
    [['battery_temperature','Battery Temperature','°C'],['battery_soc','Battery State of Charge','%'],['torso_temperature','Torso Temperature','°C'],['imu_pitch','IMU Pitch','°'],['imu_roll','IMU Roll','°'],['left_leg_torque','Left Leg Torque','Nm'],['right_leg_torque','Right Leg Torque','Nm'],['left_arm_torque','Left Arm Torque','Nm'],['right_arm_torque','Right Arm Torque','Nm'],['controller_temperature','Controller Temperature','°C']],
    ['battery_temperature','battery_soc','left_leg_torque','right_leg_torque','controller_temperature'], ['fall_detected','balance_loss','battery_overtemperature','joint_overload','perception_fault','emergency_stop'],
    [{signal:'battery_temperature',label:'Battery overtemperature',warning:[0,45],shutdown:[0,55]},{signal:'battery_soc',label:'Low battery',warning:[20,100],shutdown:[10,100]}]),
}

export function getRobotProfile(type) { return ROBOT_PROFILES[type] || ROBOT_PROFILES.articulated }
