import { getRobotProfile } from './robotProfiles.js'

const common = {
  safetySignals: ['temperature','vibration','current','load'],
  intelligenceSignals: ['temperature','vibration','current','load'],
  predictionSignals: ['temperature','vibration','current','load'],
  tabs: ['Overview','Components','Safety','Health','Predictions','Maintenance','Telemetry'],
}
const p = (id, name, subtitle, components, telemetry, safety, predictions, hazards) => ({ ...common, id, name, subtitle, components, telemetry, safety, predictions, hazards })

export const SPECIALIZED_MACHINE_PROFILES = {
  cnc: p('cnc','CNC Machine','Precision machining · spindle, axes and tooling',['Spindle','X Axis','Y Axis','Z Axis','Tool Holder','Coolant System','Controller'],[['spindle_rpm','Spindle RPM','rpm'],['spindle_load','Spindle Load','%'],['spindle_temperature','Spindle Temperature','°C'],['spindle_vibration','Spindle Vibration','g'],['x_position','X Position','mm'],['y_position','Y Position','mm'],['z_position','Z Position','mm'],['tool_life','Tool Life','%'],['coolant_temperature','Coolant Temperature','°C'],['coolant_flow','Coolant Flow','L/min']],[{signal:'spindle_temperature',label:'Spindle overtemperature',warning:[60,75],shutdown:[0,85]},{signal:'spindle_vibration',label:'Excess spindle vibration',warning:[0,2],shutdown:[0,3]},{signal:'spindle_rpm',label:'Spindle overspeed',warning:[0,12000],shutdown:[0,15000]},{signal:'coolant_flow',label:'Coolant loss',warning:[2,99999],shutdown:[0,1]}],['spindle_temperature','spindle_vibration','spindle_load','tool_life'],['overspeed','overtemperature','excess_vibration','coolant_loss','axis_fault','enclosure_interlock']),
  robot: p('robot','Industrial Robot','Select a robot architecture to load its engineering profile',[],[],[],[],[]),
  drill_press: p('drill_press','Drill Press','Spindle, feed and drilling force',['Spindle','Chuck','Feed Mechanism','Motor','Coolant System'],[['rpm','Spindle RPM','rpm'],['temperature','Spindle Temperature','°C'],['vibration','Vibration','g'],['load','Motor Load','%'],['feed_rate','Feed Rate','mm/min'],['depth','Depth','mm'],['force','Drilling Force','N'],['coolant','Coolant Flow','L/min']],[{signal:'temperature',label:'Spindle overtemperature',warning:[10,55],shutdown:[0,65]},{signal:'vibration',label:'Excess vibration',warning:[0,2],shutdown:[0,3]},{signal:'load',label:'Motor overload',warning:[0,80],shutdown:[0,95]}],['temperature','vibration','load','force'],['overspeed','overload','excess_vibration','guard_interlock','emergency_stop']),
  grinding_machine: p('grinding_machine','Grinding Machine','Grinding wheel, dressing and thermal condition',['Grinding Spindle','Grinding Wheel','Dresser','Table','Coolant System','Drive'],[['spindle_rpm','Spindle RPM','rpm'],['grinding_load','Grinding Load','%'],['vibration','Vibration','g'],['temperature','Spindle Temperature','°C'],['wheel_speed','Wheel Speed','m/s'],['wheel_life','Wheel Life','%'],['dressing','Dressing State','state'],['coolant_flow','Coolant Flow','L/min']],[{signal:'temperature',label:'Spindle overtemperature',warning:[10,55],shutdown:[0,65]},{signal:'vibration',label:'Wheel imbalance',warning:[0,2],shutdown:[0,3]},{signal:'grinding_load',label:'Grinding overload',warning:[0,80],shutdown:[0,95]}],['vibration','temperature','grinding_load','wheel_life'],['wheel_burst','imbalance','overload','coolant_loss','guard_interlock']),
  hydraulic_press: p('hydraulic_press','Hydraulic Press','Hydraulic power, ram position and force',['Hydraulic Pump','Reservoir','Valves','Cylinder/Ram','Pressure System','Controller'],[['pressure','Hydraulic Pressure','bar'],['oil_temperature','Oil Temperature','°C'],['flow','Hydraulic Flow','L/min'],['pump_load','Pump Load','%'],['position','Ram Position','mm'],['force','Press Force','kN'],['speed','Ram Speed','mm/s'],['cycle','Cycle State','state']],[{signal:'pressure',label:'Hydraulic overpressure',warning:[0,180],shutdown:[0,210]},{signal:'oil_temperature',label:'Oil overtemperature',warning:[10,65],shutdown:[0,80]},{signal:'pump_load',label:'Pump overload',warning:[0,80],shutdown:[0,95]}],['pressure','oil_temperature','pump_load','force'],['overpressure','ram_fault','oil_overtemperature','pump_overload','guard_interlock','emergency_stop']),
  injection_molding: p('injection_molding','Injection Molding Machine','Injection unit, mold and clamp',['Injection Unit','Screw','Barrel Heater','Mold','Clamp Unit','Hydraulic System','Cooling System'],[['injection_pressure','Injection Pressure','bar'],['screw_speed','Screw Speed','rpm'],['injection_time','Injection Time','s'],['back_pressure','Back Pressure','bar'],['mold_temperature','Mold Temperature','°C'],['clamp_force','Clamp Force','kN'],['mold_position','Mold Position','mm'],['cycle_time','Cycle Time','s']],[{signal:'injection_pressure',label:'Injection overpressure',warning:[0,150],shutdown:[0,180]},{signal:'mold_temperature',label:'Mold overtemperature',warning:[10,80],shutdown:[0,95]},{signal:'clamp_force',label:'Clamp overload',warning:[0,90],shutdown:[0,105]}],['injection_pressure','mold_temperature','cycle_time','clamp_force'],['overpressure','heater_overtemperature','clamp_fault','mold_interlock','emergency_stop']),
  packaging_machine: p('packaging_machine','Packaging Machine','Line speed, sealing, cutting and rejects',['Infeed','Conveyor','Sealer','Cutter','Printer/Marker','Reject System','Controller'],[['line_speed','Line Speed','m/min'],['throughput','Throughput','units/min'],['cycle_time','Cycle Time','s'],['utilization','Utilization','%'],['feed','Feed State','state'],['seal','Seal Temperature','°C'],['cut','Cutter State','state'],['reject_rate','Reject Rate','%']],[{signal:'seal',label:'Sealer overtemperature',warning:[20,180],shutdown:[0,210]},{signal:'utilization',label:'Line overload',warning:[0,90],shutdown:[0,100]}],['line_speed','throughput','cycle_time','reject_rate'],['jam','cutter_fault','sealer_overtemperature','guard_interlock','emergency_stop']),
  generator: p('generator','Generator','Engine, alternator, fuel and electrical output',['Engine','Alternator','Fuel System','Cooling System','Lubrication','Battery','Controller'],[['output_power','Output Power','kW'],['voltage','Voltage','V'],['current','Current','A'],['frequency','Frequency','Hz'],['rpm','Engine RPM','rpm'],['oil_pressure','Oil Pressure','bar'],['oil_temperature','Oil Temperature','°C'],['load','Electrical Load','%']],[{signal:'oil_pressure',label:'Low oil pressure',warning:[2,999],shutdown:[1,999]},{signal:'oil_temperature',label:'Oil overtemperature',warning:[10,95],shutdown:[0,110]},{signal:'frequency',label:'Frequency out of range',warning:[45,55],shutdown:[40,60]},{signal:'load',label:'Generator overload',warning:[0,90],shutdown:[0,100]}],['oil_pressure','oil_temperature','load','frequency'],['overspeed','low_oil_pressure','overtemperature','overload','overfrequency','underfrequency']),
  transformer: p('transformer','Transformer','Electrical loading, winding and thermal condition',['HV Winding','LV Winding','Core','Oil Tank','Cooling System','Bushings','Protection Relay'],[['primary_voltage','Primary Voltage','kV'],['secondary_voltage','Secondary Voltage','kV'],['current','Current','A'],['load','Load','%'],['top_oil_temperature','Top Oil Temperature','°C'],['winding_temperature','Winding Temperature','°C'],['ambient','Ambient Temperature','°C'],['cooling_state','Cooling State','state']],[{signal:'top_oil_temperature',label:'Top-oil overtemperature',warning:[10,85],shutdown:[0,100]},{signal:'winding_temperature',label:'Winding overtemperature',warning:[10,100],shutdown:[0,120]},{signal:'load',label:'Transformer overload',warning:[0,100],shutdown:[0,120]}],['top_oil_temperature','winding_temperature','load','current'],['overtemperature','overload','protection_trip','cooling_failure']),
  boiler: p('boiler','Boiler','Steam, combustion, fuel and burner safety',['Burner','Boiler Drum','Feedwater Pump','Steam System','Fuel System','Air System','Safety Valve'],[['pressure','Steam Pressure','bar'],['temperature','Steam Temperature','°C'],['flow','Steam Flow','t/h'],['steam_quality','Steam Quality','%'],['flame_state','Flame State','state'],['fuel_flow','Fuel Flow','kg/h'],['air_flow','Air Flow','kg/h'],['burner_load','Burner Load','%']],[{signal:'pressure',label:'Steam overpressure',warning:[0,12],shutdown:[0,15]},{signal:'temperature',label:'Steam overtemperature',warning:[10,300],shutdown:[0,330]},{signal:'flame_state',label:'Flame failure',warning:[1,1],shutdown:[0,0]}],['pressure','temperature','fuel_flow','burner_load'],['overpressure','flame_failure','low_water','fuel_fault','air_fault','safety_valve']),
  furnace: p('furnace','Furnace / Oven','Heating zones and controlled thermal profile',['Chamber','Heater/Burner','Zone 1','Zone 2','Zone 3','Exhaust','Controller'],[['chamber_temperature','Chamber Temperature','°C'],['setpoint','Setpoint','°C'],['temperature_spread','Temperature Spread','°C'],['ramp_rate','Ramp Rate','°C/min'],['heater_load','Heater Load','%'],['zone_1','Zone 1','°C'],['zone_2','Zone 2','°C'],['zone_3','Zone 3','°C']],[{signal:'chamber_temperature',label:'Chamber overtemperature',warning:[0,850],shutdown:[0,900]},{signal:'heater_load',label:'Heater overload',warning:[0,90],shutdown:[0,100]}],['chamber_temperature','temperature_spread','ramp_rate','heater_load'],['overtemperature','heater_fault','burner_fault','exhaust_fault','door_interlock']),
  hvac: p('hvac','HVAC Unit','Compressor, heat exchange and airflow',['Compressor','Condenser','Evaporator','Supply Fan','Return Fan','Expansion Device','Controller'],[['supply_temperature','Supply Temperature','°C'],['return_temperature','Return Temperature','°C'],['setpoint','Setpoint','°C'],['capacity','Capacity','%'],['supply_flow','Supply Flow','m3/h'],['return_flow','Return Flow','m3/h'],['static_pressure','Static Pressure','Pa'],['compressor_load','Compressor Load','%']],[{signal:'compressor_load',label:'Compressor overload',warning:[0,85],shutdown:[0,100]},{signal:'supply_temperature',label:'Supply temperature high',warning:[5,35],shutdown:[0,45]}],['compressor_load','supply_temperature','return_temperature','static_pressure'],['compressor_overload','high_pressure','low_pressure','fan_fault','overtemperature']),
  fan_blower: p('fan_blower','Fan / Blower','Drive, impeller, airflow and pressure',['Motor','Impeller','Bearings','Drive','Damper','Ducting'],[['rpm','RPM','rpm'],['motor_current','Motor Current','A'],['motor_temperature','Motor Temperature','°C'],['vibration','Vibration','g'],['flow','Air Flow','m3/h'],['pressure','Pressure','Pa'],['damper_position','Damper Position','%'],['efficiency','Efficiency','%']],[{signal:'motor_temperature',label:'Motor overtemperature',warning:[10,80],shutdown:[0,95]},{signal:'vibration',label:'Excess vibration',warning:[0,2],shutdown:[0,3]},{signal:'motor_current',label:'Motor overcurrent',warning:[0,80],shutdown:[0,100]}],['vibration','motor_temperature','motor_current','efficiency'],['overspeed','bearing_fault','imbalance','overtemperature','overcurrent']),
  gearbox: p('gearbox','Gearbox','Gears, shafts, bearings and lubrication',['Input Shaft','Gears','Output Shaft','Bearings','Lubrication System','Housing'],[['input_rpm','Input RPM','rpm'],['output_rpm','Output RPM','rpm'],['torque','Torque','Nm'],['load','Load','%'],['oil_temperature','Oil Temperature','°C'],['oil_level','Oil Level','%'],['oil_pressure','Oil Pressure','bar'],['particle_level','Particle Level','count']],[{signal:'oil_temperature',label:'Gearbox oil overtemperature',warning:[10,80],shutdown:[0,95]},{signal:'load',label:'Gearbox overload',warning:[0,85],shutdown:[0,100]},{signal:'particle_level',label:'Lubricant contamination',warning:[0,100],shutdown:[0,200]}],['vibration','oil_temperature','torque','particle_level'],['overspeed','overload','bearing_fault','lubrication_failure','overtemperature']),
  turbine: p('turbine','Turbine','Rotor, bearings, thermal and lubrication systems',['Rotor','Bearings','Steam/Gas Path','Generator Coupling','Lubrication','Control Valves'],[['rpm','Rotor Speed','rpm'],['vibration','Vibration','g'],['axial_position','Axial Position','mm'],['load','Load','%'],['inlet_temperature','Inlet Temperature','°C'],['outlet_temperature','Outlet Temperature','°C'],['pressure','Inlet Pressure','bar'],['oil_pressure','Oil Pressure','bar']],[{signal:'vibration',label:'Excess rotor vibration',warning:[0,2],shutdown:[0,3]},{signal:'rpm',label:'Rotor overspeed',warning:[0,3000],shutdown:[0,3300]},{signal:'oil_pressure',label:'Low oil pressure',warning:[2,999],shutdown:[1,999]}],['vibration','rpm','oil_pressure','load'],['overspeed','excess_vibration','axial_shift','low_oil_pressure','overtemperature']),
  crane_hoist: p('crane_hoist','Crane / Hoist','Hoisting, load handling, travel and braking',['Hoist Motor','Brake','Rope/Chain','Drum','Trolley','Bridge Drive','Load Sensor','Limit Switches'],[['load','Load','kg'],['hoist_speed','Hoist Speed','m/min'],['motor_current','Motor Current','A'],['brake_state','Brake State','state'],['travel_speed','Travel Speed','m/min'],['position','Position','m'],['motor_load','Motor Load','%'],['overload_state','Overload State','state']],[{signal:'motor_load',label:'Hoist motor overload',warning:[0,85],shutdown:[0,100]},{signal:'load',label:'Rated load exceeded',warning:[0,95],shutdown:[0,100]}],['load','motor_current','motor_load','position'],['overload','brake_failure','limit_fault','rope_fault','collision']),
  agv_amr: p('agv_amr','AGV / AMR','Autonomous navigation, drive and battery',['Navigation','Left Drive','Right Drive','Battery','Safety Scanner','Controller','Payload'],[['location','Location','state'],['route','Route','state'],['navigation_state','Navigation State','state'],['obstacle_state','Obstacle State','state'],['left_motor','Left Motor','%'],['right_motor','Right Motor','%'],['speed','Speed','m/s'],['drive_load','Drive Load','%'],['state_of_charge','State of Charge','%'],['battery_temperature','Battery Temperature','°C']],[{signal:'battery_temperature',label:'Battery overtemperature',warning:[10,45],shutdown:[0,55]},{signal:'state_of_charge',label:'Low battery',warning:[20,100],shutdown:[10,100]},{signal:'drive_load',label:'Drive overload',warning:[0,85],shutdown:[0,100]}],['battery_temperature','state_of_charge','drive_load','speed'],['obstacle_detected','navigation_fault','drive_fault','battery_overtemperature','low_battery']),
  water_treatment: p('water_treatment','Water Treatment System','Pumps, tanks, dosing and water quality',['Inlet Pump','Process Tank','Filter','Dosing System','Valves','Outlet Pump','Sensors','Controller'],[['ph','pH','pH'],['turbidity','Turbidity','NTU'],['conductivity','Conductivity','uS/cm'],['temperature','Temperature','°C'],['flow','Flow','m3/h'],['pressure','Pressure','bar'],['tank_level','Tank Level','%'],['chemical_dose','Chemical Dose','L/h']],[{signal:'tank_level',label:'Tank level limit',warning:[10,90],shutdown:[5,98]},{signal:'pressure',label:'Process overpressure',warning:[0,6],shutdown:[0,8]},{signal:'temperature',label:'Process overtemperature',warning:[5,45],shutdown:[0,55]}],['ph','turbidity','conductivity','flow'],['overpressure','tank_overflow','pump_fault','chemical_fault','sensor_fault']),
  other: p('other','Custom Machine','Configurable specialized machine',['Primary Drive','Controller','Process System','Safety System'],[['temperature','Temperature','°C'],['vibration','Vibration','g'],['current','Current','A'],['load','Load','%'],['pressure','Pressure','bar'],['speed','Speed','rpm'],['flow','Flow','L/min']],[{signal:'temperature',label:'Overtemperature',warning:[10,40],shutdown:[0,45]},{signal:'vibration',label:'Excess vibration',warning:[0,2],shutdown:[0,3]},{signal:'current',label:'Overcurrent',warning:[0,8],shutdown:[0,12]},{signal:'load',label:'Overload',warning:[0,80],shutdown:[0,95]}],['temperature','vibration','current','load'],['overtemperature','overload','excess_vibration','emergency_stop']),
}

export function getSpecializedMachineProfile(category) {
  const raw = String(category || 'other')
  if (raw.startsWith('robot_')) {
    const type = raw.slice(6)
    const rp = getRobotProfile(type)
    return { ...common, ...rp, id: `robot_${type}`, name: rp.name, subtitle: rp.architecture, components: rp.components, telemetry: rp.telemetry, safety: rp.safety, predictions: rp.predictions, hazards: rp.hazards }
  }
  return SPECIALIZED_MACHINE_PROFILES[raw] || SPECIALIZED_MACHINE_PROFILES.other
}
